# Generated by Django 3.2 on 2025-04-09 10:37

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_postfile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postfile',
            name='file',
            field=models.FileField(upload_to='file/post_file', validators=[posts.models.validate_file_type]),
        ),
    ]
