version: '3.8'

services:

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
      MYSQL_ROOT_PASSWORD: myrootpassword
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    networks:
      - django_network

  
  web:
    build: .
    command: sh -c "python manage.py migrate && gunicorn --config gunicorn.conf.py Bit_gram.wsgi:application"
    environment:
      DB_HOST: db
      DB_NAME: mydb
      DB_USER: myuser
      DB_PASSWORD: mypassword
    volumes:
      - ./:/app
    depends_on:
      - db
    networks:
      - django_network

  
  services:
  nginx:
    volumes:
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
      - type: bind
        source: ./static
        target: /static
      - type: bind
        source: ./media
        target: /media

volumes:
  mysql_data:

networks:
  django_network:
    driver: bridge