version: '3'

services:
  db:
    image: mysql:5.7
    container_name: bitgram_db
    volumes:
      - db_data:/var/lib/mysql/data
    restart: always
    env_file: .env  # فرض وجود فایل .env در کنار docker-compose.yml
    ports:
      - "3306:3306"
    networks:
      - bitgram_network

  web:
    build: .
    container_name: bitgram_web
    command: gunicorn myproject.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    expose:
      - 8000
    depends_on:
      - db
    networks:
      - bitgram_network
      - nginx_network

  nginx:
    image: nginx:latest
    container_name: bitgram_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/usr/share/nginx/html/static
      - media_volume:/usr/share/nginx/html/media
    depends_on:
      - web
    networks:
      - nginx_network

volumes:
  db_data:
  static_volume:
  media_volume:

networks:
  bitgram_network:
  nginx_network: